### ISSUE TITLE
Problem with execution

### ISSUE THREAD

**Issue by Mahantor** [kryptonbutterfly/TinyTotp#1]
![Screenshot 2025-01-01 205402](https://github.com/user-attachments/assets/7a232fcc-e8f9-448f-a0c7-a86ffc0ef87a)

**Comment by kryptonbutterfly** [comment]
Thank you for the report.

Please attempt to run the program from a command line and post the output.

Command to run the program:
```bat
java -jar TinyTotp.jar
```

Make sure to run the command from the folder where the .jar file is located.

## Possible Causes and Solutions
<table>
<tr><th>Cause</th><th>Solution</th><tr>
<tr><td>corrupted jar file</td><td>redownload the latest <a href="https://github.com/kryptonbutterfly/TinyTotp/releases/download/v4.1.0/TinyTotp.jar">TinyTotp.jar</a> file</td></tr>
<tr><td>some problem with your java setup, causing javaw to be used to execute jars instead of java</td><td>? not sure myself ?</td></tr>
<tr><td>java version < 18</td><td>uninstall old version & install new one</td></tr>
</table>

**Comment by Mahantor** [comment]
java -jar TinyTotp.jar
With this command, the program was executed, but it is not directly executable
![sshot-1](https://github.com/user-attachments/assets/cc3d7276-c7cc-43cd-a25b-f4184eb9ad14)

Another problem I have is that:
I have a 2FA app on my phone, I copied the authenticators and entered them into TinyTotp, but the problem is that the codes generated in TinyTotp are different from the codes generated in my phone, and the codes generated in TinyTotp are not accepted on any site.

**Comment by kryptonbutterfly** [comment]
So why running the app with double click doesn't work has something to do with your java setup.

Several different options that might fix that issue:
* check your PATH variable in Windows (There are several different ones for each user as far as i know)
The PATH variable is supposed to be a `;` delimited list of elements. Some programs fail to add the delimiter when adding themselves to that variable. [How to set the variable](https://explainjava.com/set-java-path-and-java-home-windows)
Make sure to save your the old value in a text file so you can revert the changes if you make a mistake.
* check your JAVA_HOME variable in Windows and make sure it points to the jvm's java executable.
* Uninstall java and then install it again.
* The last possible solution i found is [this](https://johann.loefflmann.net/en/software/jarfix/index.html).
No idea if the tool works with modern java / windows and I can't test it since i don't have a windows system.

Regarding the codes I'm currently fixing some issues with that. So the next version should hopefully resolve that issue as well.

**Comment by kryptonbutterfly** [comment]
Alright the new version 4.2.0 is out here's the link: [TinyTotp.jar](https://github.com/kryptonbutterfly/TinyTotp/releases/download/v4.2.0/TinyTotp.jar)

This should solve the problem with importing codes.

**Comment by Mahantor** [comment]
This problem still exists

https://github.com/user-attachments/assets/9ddc1b17-3a2c-48b4-b730-7ef7ba5badb9

**Comment by kryptonbutterfly** [comment]
Did you add the entries by scanning a qr code or did you enter them by hand?

**Comment by Mahantor** [comment]
I tried both methods and the result was the same

**Comment by kryptonbutterfly** [comment]
This is how my github entry looks like.
The secret in the screenshot is `Hello, World!` base32 encoded.
The `=` in the end seem to be padding and might not be required.

I'd expect yours to also have `SHA1` as hash algorithm and `30` be the password interval

![example](https://github.com/user-attachments/assets/748a6d9c-144b-40fb-899d-a2bafb261e46)

**Comment by kryptonbutterfly** [comment]
Ok so i generated a dummy secret.
Try importing that into your app and then generate a qr code from within the app and post it.
I suspect that the app encodes the data in a way TinyTOTP doesn't know how to handle.

## Dummy Data

<table>
<tr><td>Account Name</td><td>

```
dummy@example.test
```

</td></tr><tr><td>Issuer</td><td>

```
kryptonbutterfly
```

</td></tr><tr><td>Secret</td><td>

```
F6O6IAJAYOCSCAGB
```

</td></tr><tr><td>Algorithm</td><td>SHA1</td></tr>
<tr><td>Password Interval</td><td>30</td></tr>
<tr><td>Password length</td><td>6</td></tr>
</table>

### Minimal OTP URI

```
otpauth://totp/dummy@example.test?secret=F6O6IAJAYOCSCAGB&issuer=kryptonbutterfly
```

![qr_dummy@example test](https://github.com/user-attachments/assets/2033435f-7644-4e46-9a59-25501e85335a)


### Explicite OTP URI

```
otpauth://totp/dummy@example.test?secret=F6O6IAJAYOCSCAGB&issuer=kryptonbutterfly&algorithm=SHA1&digits=6&period=30
```

![long_qr_dummy@example test](https://github.com/user-attachments/assets/40a83344-7373-4970-8665-f4909f81cb37)

**Comment by Mahantor** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/d86881b3-853e-49b3-85d9-e6099d6550c1)

**Comment by kryptonbutterfly** [comment]
Ah i meant the other app you use

**Comment by Mahantor** [comment]
sorry
![Screenshot_2025-01-11-21-08-37-935_me jmh authenticatorpro (2)](https://github.com/user-attachments/assets/936d226c-626c-4f3a-a4e2-212f2556ca9d)


otpauth://totp/kryptonbutterfly%3Adummy%40example.test?secret=F6O6IAJAYOCSCAGB&issuer=kryptonbutterfly

**Comment by kryptonbutterfly** [comment]
Please check if your system time is correct (If it's off by more than a couple of seconds that would explain the behavior).
If that doesn't solve the problem I'm fresh out of ideas.

**Comment by Mahantor** [comment]
I synced Windows time and now the problem is solved
thank you

**Comment by Mahantor** [comment]
When I closed the program and reopened it, I encountered the same problem again

**Comment by kryptonbutterfly** [comment]
Glad to hear.
And thank you for reporting the issue.
